Fix sliders
NikitaMelnychencko/eleanshop pull request #116
Opened 2021-12-06 22:49 UTC by Viktor-Kostiuchenko

1) Вынес слайдеры (кроме тех, что делала Ира) в отдельный файл slider.js
P.S. у меня на локальном слайдеры Иры тоже слайдеры работали (правда через раз)
2) Все слайдеры берут данные из slider.min.js, а не из разных как было ранее
3) Пофиксил (относительно) стили под видео-слайдеры

2021-12-13 07:30 UTC, vtyshchenko requested changes

2021-12-13 07:30 UTC, vtyshchenko commented on src/js/layout/product/infoAboutProduct.js
> +console.log(parsedProductInfoData);
видалити

2021-12-13 07:30 UTC, vtyshchenko commented on src/js/layout/product/infoAboutProduct.js
> +  console.log(parsedProductInfoData);
видалити

2021-12-13 07:30 UTC, vtyshchenko commented on src/sass/layout/fitting/_sizrTable.scss
>    }
може файл потрібно переіменувати?
_sizeTable.scss

2021-12-18 00:32 UTC, Viktor-Kostiuchenko commented on src/js/layout/product/infoAboutProduct.js
> +console.log(parsedProductInfoData);
исправил в другой ветке (Update product images)

2021-12-18 00:32 UTC, Viktor-Kostiuchenko commented on src/js/layout/product/infoAboutProduct.js
> +  console.log(parsedProductInfoData);
исправил в другой ветке (Update product images)

2021-12-18 00:33 UTC, Viktor-Kostiuchenko commented on src/sass/layout/fitting/_sizrTable.scss
>    }
исправлено

2021-12-19 17:46 UTC, closed without merging