Update product images
NikitaMelnychencko/eleanshop pull request #118
Opened 2021-12-08 00:04 UTC by Viktor-Kostiuchenko

1) исправил отображение картинок в корзине
2) исходя из текущего json сделал отрисовку картинок продукта

2021-12-13 07:34 UTC, vtyshchenko requested changes

2021-12-13 07:34 UTC, vtyshchenko commented on src/views/partials/product/productSlider.hbs
> +    <li class="product-slider-smaller__item">
для чого убрали each і написали стільки однакового коду?

2021-12-13 07:34 UTC, vtyshchenko commented on src/views/partials/product/productSlider.hbs
> +    <li class="product-slider__item">
для чого убрали each і написали стільки однакового коду?

2021-12-16 01:36 UTC, Viktor-Kostiuchenko commented on src/views/partials/product/productSlider.hbs
> +    <li class="product-slider-smaller__item">
Це було тимчасове рішення, оскільки з Локал стореджу не приходив саме масив картинок. Тепер json оновили і я відповідно назад повернув

2021-12-16 01:36 UTC, Viktor-Kostiuchenko commented on src/views/partials/product/productSlider.hbs
> +    <li class="product-slider__item">
Це було тимчасове рішення, оскільки з Локал стореджу не приходив саме масив картинок. Тепер json оновили і я відповідно назад повернув

2021-12-20 12:48 UTC, NikitaMelnychencko approved these changes

2021-12-20 12:48 UTC, NikitaMelnychencko approved these changes

2021-12-20 12:49 UTC, merged