modalRutern-delivery-pay
NikitaMelnychencko/eleanshop pull request #122
Opened 2021-12-12 15:51 UTC by LarysaTymoshenko

2021-12-13 07:39 UTC, vtyshchenko requested changes

2021-12-13 07:39 UTC, vtyshchenko commented on src/sass/layout/delivery/_deliveryTypes.scss
> +// .modal__body {
якщо не потрібне далі буде, то видалити закоментований код ( у всьому файлі)

2021-12-13 07:39 UTC, vtyshchenko commented on src/sass/layout/delivery/_deliveryTypes.scss
> +h2 {
так краще не робити, бо перебиваються стилі для h2 по сьому сайту. Краще використовуйте класи

2021-12-13 07:39 UTC, vtyshchenko commented on src/sass/layout/delivery/_formsQuestion.scss
> -  // opacity: 0;
видалити

2021-12-14 21:15 UTC, LarysaTymoshenko commented on src/sass/layout/delivery/_deliveryTypes.scss
> +// .modal__body {
Я все поправила. Просмотрите, пожалуйста

2021-12-15 13:12 UTC, vtyshchenko approved these changes

2021-12-15 13:12 UTC, vtyshchenko commented on src/sass/layout/delivery/_questionsAndAnswers.scss
> +  // border: 1px solid $button-hover-background-color;
те, що не потрібно видаляйте

2021-12-15 13:12 UTC, merged