feature/product-slider
NikitaMelnychencko/eleanshop pull request #30
Opened 2021-09-29 01:47 UTC by Viktor-Kostiuchenko

2021-09-30 20:14 UTC, vtyshchenko approved these changes

2021-09-30 20:14 UTC, vtyshchenko commented on src/js/layout/product/productSlider.js
> +// import '../../../sass/layout/product/_productSlider.scss'
код непотрібний видаляти потрібно

2021-10-01 00:35 UTC, Viktor-Kostiuchenko commented on src/js/layout/product/productSlider.js
> +// import '../../../sass/layout/product/_productSlider.scss'
Согласен. Убрал)

2021-10-01 08:22 UTC, vtyshchenko requested changes

2021-10-01 08:22 UTC, vtyshchenko commented on src/sass/layout/product/_productSlider.scss
> +// !--------------------------------------------- КОНЕЦ О ТОВАРЕ//
всі коментарі англійською

2021-10-01 08:22 UTC, vtyshchenko commented on src/sass/layout/product/_productSlider.scss
> +  font-family: Jost;
всі шрифти і кольори - константи з _variables.scss

2021-10-01 08:22 UTC, vtyshchenko commented on src/sass/layout/product/_productSlider.scss
> +  background-color: #ffffff;
константа. Значення кольору використовувати не можна
Передивіться весь файл

2021-10-01 08:22 UTC, vtyshchenko commented on src/views/partials/product/productSlider.hbs
> +                {{!-- {{#each params}} --}}
якщо не потрібно, то видалити

2021-10-01 20:11 UTC, Viktor-Kostiuchenko commented on src/sass/layout/product/_productSlider.scss
> +// !--------------------------------------------- КОНЕЦ О ТОВАРЕ//
have made in English!)

2021-10-01 20:14 UTC, Viktor-Kostiuchenko commented on src/sass/layout/product/_productSlider.scss
> +  background-color: #ffffff;
Убрал такие цвета для бекграунда

2021-10-01 20:15 UTC, Viktor-Kostiuchenko commented on src/views/partials/product/productSlider.hbs
> +                {{!-- {{#each params}} --}}
Временно убрал. Себе оставил коммент для того, чтобы не забыть перевести на шаблон создание этих лишек

2021-10-01 20:17 UTC, Viktor-Kostiuchenko commented on src/sass/layout/product/_productSlider.scss
> +  font-family: Jost;
да, использовал тогда так, потому что были траблы с подключением переменных. Сейчас перевел

2021-10-03 09:53 UTC, vtyshchenko requested changes

2021-10-03 09:53 UTC, vtyshchenko commented on src/js/layout/product/infoAboutProduct.js
> +refs.mainEL.insertAdjacentHTML('beforeend', productInfoMarkup)
цього робити не потрібно. Просто зроби експорт productInfoMarkup

2021-10-03 10:07 UTC, vtyshchenko requested changes
виправ

2021-10-03 12:17 UTC, Viktor-Kostiuchenko commented on src/views/partials/product/infoAboutProduct.hbs
> +    {{> productSlider}}
Это я в документации прочел о том, как вставлять другие паршалы шаблонов в текущий шаблон
https://handlebarsjs.com/guide/partials.html#basic-partials

2021-10-03 14:52 UTC, Viktor-Kostiuchenko commented on src/js/layout/product/infoAboutProduct.js
> +refs.mainEL.insertAdjacentHTML('beforeend', productInfoMarkup)
Переделали

2021-10-03 19:07 UTC, vtyshchenko requested changes

2021-10-03 19:07 UTC, vtyshchenko commented on src/js/layout/product/infoAboutProduct.js
> +// потом УБРАТЬ!!
чому не убрав?

2021-10-03 19:07 UTC, vtyshchenko commented on src/sass/layout/product/_infoAboutProduct.scss
> +  background-color: #ffffff;
через змінну колір

2021-10-03 22:40 UTC, Viktor-Kostiuchenko commented on src/js/layout/product/infoAboutProduct.js
> +// потом УБРАТЬ!!
теперь убрал

2021-10-03 22:42 UTC, Viktor-Kostiuchenko commented on src/sass/layout/product/_infoAboutProduct.scss
> +  background-color: #ffffff;
есть

2021-10-04 18:57 UTC, vtyshchenko approved these changes

2021-10-05 19:56 UTC, merged