Product bin
NikitaMelnychencko/eleanshop pull request #39
Opened 2021-09-30 09:10 UTC by IrinaShushkevych

2021-09-30 19:57 UTC, vtyshchenko requested changes

2021-09-30 19:57 UTC, vtyshchenko commented on src/js/layout/product/productBin.js
> +  constructor({ root = 'header', typeInsert = 'beforeEnd', data = dataBin, callback }) {
callback - прибрати звідси

2021-09-30 19:57 UTC, vtyshchenko commented on src/js/layout/product/productBin.js
> +    this.callback = callback;
переписати

2021-09-30 19:57 UTC, vtyshchenko commented on src/js/layout/product/productBin.js
> +      this.callback();
переписати

2021-09-30 19:57 UTC, vtyshchenko commented on src/sass/components/_button.scss
> +  font-family: 'Jost';
взяти змінну з _fonts.scss

2021-09-30 19:57 UTC, vtyshchenko commented on src/sass/layout/product/_productBin.scss
> +  z-index: 9999;
index великий

2021-09-30 19:57 UTC, vtyshchenko commented on src/sass/components/_button.scss
>  %button-line {
перенести до _placeholder.scss

2021-10-01 05:32 UTC, IrinaShushkevych commented on src/js/layout/product/productBin.js
> +  constructor({ root = 'header', typeInsert = 'beforeEnd', data = dataBin, callback }) {
Виконано

2021-10-01 05:32 UTC, IrinaShushkevych commented on src/js/layout/product/productBin.js
> +    this.callback = callback;
Виконано

2021-10-01 05:32 UTC, IrinaShushkevych commented on src/js/layout/product/productBin.js
> +      this.callback();
Виконано

2021-10-01 05:32 UTC, IrinaShushkevych commented on src/sass/components/_button.scss
> +  font-family: 'Jost';
Виконано

2021-10-01 05:32 UTC, IrinaShushkevych commented on src/sass/layout/product/_productBin.scss
> +  z-index: 9999;
Виконано

2021-10-01 05:33 UTC, IrinaShushkevych commented on src/sass/components/_button.scss
>  %button-line {
Нажаль не можу це зробити, оскільки це не мій код.

2021-10-01 08:14 UTC, vtyshchenko approved these changes

2021-10-01 19:58 UTC, vtyshchenko approved these changes

2021-10-03 08:36 UTC, merged